### ISSUE TITLE
测试用例文本中有<CR>，导致字符串比对无法通过。

### ISSUE THREAD

**Issue by nuintun** [spmjs/cmd-util#15]
直接上图，求解：
![qq20140418200428](https://cloud.githubusercontent.com/assets/1730277/2741693/da79b21a-c6f1-11e3-9846-d3a4fd195bdd.png)
这是怎么回事啊？

**Comment by popomore** [comment]
设下编辑器的 line ending 为 unix 风格(LF)

**Comment by nuintun** [comment]
回去看看，脚本转换的一般不用这个换行，现在这种情况太容易跳坑了。

**Comment by popomore** [comment]
一般习惯都是用 LF，除了windows 用户 :smile:

**Comment by nuintun** [comment]
@popomore  木有linux肿么破:smile: 难道只能靠编辑器~

**Comment by army8735** [comment]
我习惯将用例中的回车给删除掉了……win和mac来回切才一致。

**Comment by popomore** [comment]
难道你 win 下用的记事本？一般编辑器都有这个设置吧，装备好才能写好代码，哈哈。

**Comment by army8735** [comment]
都是webstorm，mac下的文件到win下会自动多出回车，很奇怪。

**Comment by nuintun** [comment]
@army8735 回车大部分时候没影响，就是在像这种单元测试中比较文本的时候才会挖坑 :smile: 
@popomore 哪能用记事本，用的webstorm和sublime :smile:

**Comment by popomore** [comment]
sublime 有个配置 `default_line_ending`

**Comment by nuintun** [comment]
@popomore binggo

**Comment by nuintun** [comment]
@popomore 这里还和`git`的自动换行转换有关，用`git clone`的代码会根据系统进行换行符转换，所以在`windows`下用`git clone`的代码是无法通过用例的，要配置`git config`不做换行转换才行，囧rz

**Comment by army8735** [comment]
测试区把它正则全过滤掉，我就这样干的。否则win和mac切换不行。

**Comment by popomore** [comment]
对，git 有个设置项 crlf 的
