### ISSUE TITLE
ast.js中，获取函数名的方式有错

### ISSUE THREAD

**Issue by chx007** [spmjs/cmd-util#4]
ast.js代码中多处出现以下类似代码，用于判断代码结点是否为对函数名为require的调用，然后再获取其参数，比如模块 id

``` js
if(node instanceof UglifyJS.AST_Call && node.start.value === 'require')
```

此种方式对如下代码也能判断通过

``` js
require('module-a')('abc')
```

但是，此时 node.args[0] 其实是 'abc'，而不是 'module-a'，也就是说通过上述方式解析require 对应的模块 id 参数值，很有可能是错的

正确的方式应该是

``` js
if(node instanceof UglifyJS.AST_Call && node.expression.name === 'require') {
  var id = node.args[0].value
}
```

**Comment by lepture** [comment]
The test case https://github.com/spmjs/cmd-util/blob/master/tests/ast.test.js#L111 passed.

**Comment by lepture** [comment]
Thanks for your feedback.

You can send a pull request the next time.
