### ISSUE TITLE
require.async('jquery')能否转换到parsed.async属性中呢！

### ISSUE THREAD

**Issue by nuintun** [spmjs/cmd-util#6]
如题吧，能否把`async`依赖放到`async`属性中呢，这样便于用工具替换

``` js
require.async('jquery');
```

到完整路径

``` js
require.async('base/jquery/1.10.2/jquery');
```

把配置简化，现在`sea.config`必须保留`async`的别名配置！

**Comment by afc163** [comment]
替换但不提取，我觉得可行。

**Comment by nuintun** [comment]
@afc163 这个可以有~

**Comment by afc163** [comment]
issues-center/issues#1

**Comment by lepture** [comment]
这个用正则就好了

**Comment by nuintun** [comment]
@lepture 怕误伤啊

**Comment by popomore** [comment]
这个 @lepture 处理下吧

**Comment by lepture** [comment]
@NewtonNiu https://github.com/spmjs/cmd-util/blob/master/docs/ast.md#astmodifycode-id-fn-dependencies-fn-require-fn-async-fn

**Comment by lepture** [comment]
released in 0.3.12
